import { ChampionMastery } from "../riot-api/interfaces/champion-mastery.interface";

export const getChampionsMasteries = (userPuuid: string) => {
  return [
    {
      puuid: userPuuid,
      championId: 107,
      championLevel: 125,
      championPoints: 1340969,
      lastPlayTime: 1781731910000,
      championPointsSinceLastLevel: 369,
      championPointsUntilNextLevel: 10631,
      markRequiredForNextLevel: 2,
      tokensEarned: 36,
      championSeasonMilestone: 4,
      milestoneGrades: ['B+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'S-': 2,
        },
        rewardMarks: 1,
        bonus: true,
        totalGamesRequires: 2,
      },
    },
    {
      puuid: userPuuid,
      championId: 11,
      championLevel: 115,
      championPoints: 1241055,
      lastPlayTime: 1781419272000,
      championPointsSinceLastLevel: 10455,
      championPointsUntilNextLevel: 545,
      markRequiredForNextLevel: 2,
      tokensEarned: 46,
      championSeasonMilestone: 1,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 157,
      championLevel: 76,
      championPoints: 802362,
      lastPlayTime: 1781774368000,
      championPointsSinceLastLevel: 762,
      championPointsUntilNextLevel: 10238,
      markRequiredForNextLevel: 2,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      milestoneGrades: ['B+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 121,
      championLevel: 39,
      championPoints: 421294,
      lastPlayTime: 1780252853000,
      championPointsSinceLastLevel: 26694,
      championPointsUntilNextLevel: -15694,
      markRequiredForNextLevel: 2,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 238,
      championLevel: 38,
      championPoints: 387782,
      lastPlayTime: 1780263665000,
      championPointsSinceLastLevel: 4182,
      championPointsUntilNextLevel: 6818,
      markRequiredForNextLevel: 2,
      tokensEarned: 14,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 122,
      championLevel: 37,
      championPoints: 379601,
      lastPlayTime: 1781292859000,
      championPointsSinceLastLevel: 7001,
      championPointsUntilNextLevel: 3999,
      markRequiredForNextLevel: 2,
      tokensEarned: 22,
      championSeasonMilestone: 1,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 245,
      championLevel: 27,
      championPoints: 279005,
      lastPlayTime: 1781646869000,
      championPointsSinceLastLevel: 16405,
      championPointsUntilNextLevel: -5405,
      markRequiredForNextLevel: 2,
      tokensEarned: 0,
      championSeasonMilestone: 2,
      milestoneGrades: ['A', 'B+', 'C+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'S-': 1,
        },
        rewardMarks: 2,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 86,
      championLevel: 28,
      championPoints: 278044,
      lastPlayTime: 1778652586000,
      championPointsSinceLastLevel: 4444,
      championPointsUntilNextLevel: 6556,
      markRequiredForNextLevel: 2,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 17,
      championLevel: 20,
      championPoints: 234009,
      lastPlayTime: 1652131865000,
      championPointsSinceLastLevel: 48409,
      championPointsUntilNextLevel: -37409,
      markRequiredForNextLevel: 2,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 24,
      championLevel: 23,
      championPoints: 229399,
      lastPlayTime: 1778729332000,
      championPointsSinceLastLevel: 10799,
      championPointsUntilNextLevel: 201,
      markRequiredForNextLevel: 2,
      tokensEarned: 10,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 141,
      championLevel: 20,
      championPoints: 186879,
      lastPlayTime: 1781510750000,
      championPointsSinceLastLevel: 1279,
      championPointsUntilNextLevel: 9721,
      markRequiredForNextLevel: 2,
      tokensEarned: 4,
      championSeasonMilestone: 1,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 45,
      championLevel: 19,
      championPoints: 184345,
      lastPlayTime: 1781749761000,
      championPointsSinceLastLevel: 9745,
      championPointsUntilNextLevel: 1255,
      markRequiredForNextLevel: 2,
      tokensEarned: 8,
      championSeasonMilestone: 2,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'S-': 1,
        },
        rewardMarks: 2,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 91,
      championLevel: 17,
      championPoints: 162105,
      lastPlayTime: 1781672602000,
      championPointsSinceLastLevel: 9505,
      championPointsUntilNextLevel: 1495,
      markRequiredForNextLevel: 2,
      tokensEarned: 25,
      championSeasonMilestone: 1,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 104,
      championLevel: 16,
      championPoints: 144507,
      lastPlayTime: 1780262078000,
      championPointsSinceLastLevel: 2907,
      championPointsUntilNextLevel: 8093,
      markRequiredForNextLevel: 2,
      tokensEarned: 7,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 35,
      championLevel: 15,
      championPoints: 134269,
      lastPlayTime: 1774416949000,
      championPointsSinceLastLevel: 3669,
      championPointsUntilNextLevel: 7331,
      markRequiredForNextLevel: 2,
      tokensEarned: 6,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 517,
      championLevel: 13,
      championPoints: 119084,
      lastPlayTime: 1781708991000,
      championPointsSinceLastLevel: 10484,
      championPointsUntilNextLevel: 516,
      markRequiredForNextLevel: 2,
      tokensEarned: 18,
      championSeasonMilestone: 1,
      milestoneGrades: ['C+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 30,
      championLevel: 13,
      championPoints: 115243,
      lastPlayTime: 1781372098000,
      championPointsSinceLastLevel: 6643,
      championPointsUntilNextLevel: 4357,
      markRequiredForNextLevel: 2,
      tokensEarned: 17,
      championSeasonMilestone: 0,
      milestoneGrades: ['C+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 64,
      championLevel: 11,
      championPoints: 101371,
      lastPlayTime: 1778880604000,
      championPointsSinceLastLevel: 14771,
      championPointsUntilNextLevel: -3771,
      markRequiredForNextLevel: 2,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 29,
      championLevel: 12,
      championPoints: 100162,
      lastPlayTime: 1779171410000,
      championPointsSinceLastLevel: 2562,
      championPointsUntilNextLevel: 8438,
      markRequiredForNextLevel: 2,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 777,
      championLevel: 12,
      championPoints: 98709,
      lastPlayTime: 1781752677000,
      championPointsSinceLastLevel: 1109,
      championPointsUntilNextLevel: 9891,
      markRequiredForNextLevel: 2,
      tokensEarned: 8,
      championSeasonMilestone: 1,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 41,
      championLevel: 11,
      championPoints: 96887,
      lastPlayTime: 1770961359000,
      championPointsSinceLastLevel: 10287,
      championPointsUntilNextLevel: 713,
      markRequiredForNextLevel: 2,
      tokensEarned: 5,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 266,
      championLevel: 11,
      championPoints: 91942,
      lastPlayTime: 1781502217000,
      championPointsSinceLastLevel: 5342,
      championPointsUntilNextLevel: 5658,
      markRequiredForNextLevel: 2,
      tokensEarned: 20,
      championSeasonMilestone: 2,
      milestoneGrades: ['A+', 'B+', 'B+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'S-': 1,
        },
        rewardMarks: 2,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 234,
      championLevel: 11,
      championPoints: 91682,
      lastPlayTime: 1781331563000,
      championPointsSinceLastLevel: 5082,
      championPointsUntilNextLevel: 5918,
      markRequiredForNextLevel: 2,
      tokensEarned: 13,
      championSeasonMilestone: 0,
      milestoneGrades: ['B+', 'B'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 523,
      championLevel: 11,
      championPoints: 90094,
      lastPlayTime: 1779604812000,
      championPointsSinceLastLevel: 3494,
      championPointsUntilNextLevel: 7506,
      markRequiredForNextLevel: 2,
      tokensEarned: 27,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 13,
      championLevel: 11,
      championPoints: 89364,
      lastPlayTime: 1779481808000,
      championPointsSinceLastLevel: 2764,
      championPointsUntilNextLevel: 8236,
      markRequiredForNextLevel: 2,
      tokensEarned: 5,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 80,
      championLevel: 10,
      championPoints: 85655,
      lastPlayTime: 1779895545000,
      championPointsSinceLastLevel: 10055,
      championPointsUntilNextLevel: 945,
      markRequiredForNextLevel: 2,
      tokensEarned: 23,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 5,
      championLevel: 10,
      championPoints: 81393,
      lastPlayTime: 1779234628000,
      championPointsSinceLastLevel: 5793,
      championPointsUntilNextLevel: 5207,
      markRequiredForNextLevel: 2,
      tokensEarned: 16,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 62,
      championLevel: 10,
      championPoints: 76261,
      lastPlayTime: 1780180341000,
      championPointsSinceLastLevel: 661,
      championPointsUntilNextLevel: 10339,
      markRequiredForNextLevel: 2,
      tokensEarned: 14,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 92,
      championLevel: 9,
      championPoints: 69665,
      lastPlayTime: 1781635874000,
      championPointsSinceLastLevel: 5065,
      championPointsUntilNextLevel: 5935,
      markRequiredForNextLevel: 2,
      tokensEarned: 13,
      championSeasonMilestone: 0,
      milestoneGrades: ['B+', 'B+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 246,
      championLevel: 9,
      championPoints: 69520,
      lastPlayTime: 1781638857000,
      championPointsSinceLastLevel: 4920,
      championPointsUntilNextLevel: 6080,
      markRequiredForNextLevel: 2,
      tokensEarned: 23,
      championSeasonMilestone: 1,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 119,
      championLevel: 9,
      championPoints: 68870,
      lastPlayTime: 1779762437000,
      championPointsSinceLastLevel: 4270,
      championPointsUntilNextLevel: 6730,
      markRequiredForNextLevel: 2,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 105,
      championLevel: 9,
      championPoints: 65644,
      lastPlayTime: 1772085299000,
      championPointsSinceLastLevel: 1044,
      championPointsUntilNextLevel: 9956,
      markRequiredForNextLevel: 2,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 75,
      championLevel: 8,
      championPoints: 62644,
      lastPlayTime: 1780904715000,
      championPointsSinceLastLevel: 9044,
      championPointsUntilNextLevel: 1956,
      markRequiredForNextLevel: 1,
      tokensEarned: 8,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 112,
      championLevel: 8,
      championPoints: 61468,
      lastPlayTime: 1781298124000,
      championPointsSinceLastLevel: 7868,
      championPointsUntilNextLevel: 3132,
      markRequiredForNextLevel: 1,
      tokensEarned: 10,
      championSeasonMilestone: 1,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 203,
      championLevel: 8,
      championPoints: 61030,
      lastPlayTime: 1756430355000,
      championPointsSinceLastLevel: 7430,
      championPointsUntilNextLevel: 3570,
      markRequiredForNextLevel: 1,
      tokensEarned: 4,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 114,
      championLevel: 8,
      championPoints: 57394,
      lastPlayTime: 1766043493000,
      championPointsSinceLastLevel: 3794,
      championPointsUntilNextLevel: 7206,
      markRequiredForNextLevel: 1,
      tokensEarned: 8,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 54,
      championLevel: 8,
      championPoints: 54460,
      lastPlayTime: 1777859233000,
      championPointsSinceLastLevel: 860,
      championPointsUntilNextLevel: 10140,
      markRequiredForNextLevel: 1,
      tokensEarned: 6,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 58,
      championLevel: 8,
      championPoints: 53763,
      lastPlayTime: 1759017342000,
      championPointsSinceLastLevel: 163,
      championPointsUntilNextLevel: 10837,
      markRequiredForNextLevel: 1,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 120,
      championLevel: 7,
      championPoints: 53159,
      lastPlayTime: 1779090573000,
      championPointsSinceLastLevel: 10559,
      championPointsUntilNextLevel: 441,
      markRequiredForNextLevel: 1,
      tokensEarned: 9,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 202,
      championLevel: 7,
      championPoints: 52757,
      lastPlayTime: 1779093668000,
      championPointsSinceLastLevel: 10157,
      championPointsUntilNextLevel: 843,
      markRequiredForNextLevel: 1,
      tokensEarned: 8,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 254,
      championLevel: 7,
      championPoints: 51901,
      lastPlayTime: 1779864075000,
      championPointsSinceLastLevel: 9301,
      championPointsUntilNextLevel: 1699,
      markRequiredForNextLevel: 1,
      tokensEarned: 21,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 82,
      championLevel: 7,
      championPoints: 48211,
      lastPlayTime: 1771542029000,
      championPointsSinceLastLevel: 5611,
      championPointsUntilNextLevel: 5389,
      markRequiredForNextLevel: 1,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 555,
      championLevel: 7,
      championPoints: 46310,
      lastPlayTime: 1781776234000,
      championPointsSinceLastLevel: 3710,
      championPointsUntilNextLevel: 7290,
      markRequiredForNextLevel: 1,
      tokensEarned: 12,
      championSeasonMilestone: 0,
      milestoneGrades: ['B', 'B'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 2,
      championLevel: 7,
      championPoints: 45568,
      lastPlayTime: 1778534027000,
      championPointsSinceLastLevel: 2968,
      championPointsUntilNextLevel: 8032,
      markRequiredForNextLevel: 1,
      tokensEarned: 5,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 59,
      championLevel: 6,
      championPoints: 41385,
      lastPlayTime: 1776622927000,
      championPointsSinceLastLevel: 9785,
      championPointsUntilNextLevel: 1215,
      markRequiredForNextLevel: 1,
      tokensEarned: 12,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 63,
      championLevel: 6,
      championPoints: 39139,
      lastPlayTime: 1779080188000,
      championPointsSinceLastLevel: 7539,
      championPointsUntilNextLevel: 3461,
      markRequiredForNextLevel: 1,
      tokensEarned: 4,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 90,
      championLevel: 6,
      championPoints: 38981,
      lastPlayTime: 1781763929000,
      championPointsSinceLastLevel: 7381,
      championPointsUntilNextLevel: 3619,
      markRequiredForNextLevel: 1,
      tokensEarned: 7,
      championSeasonMilestone: 1,
      milestoneGrades: ['C+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 56,
      championLevel: 6,
      championPoints: 34928,
      lastPlayTime: 1778793788000,
      championPointsSinceLastLevel: 3328,
      championPointsUntilNextLevel: 7672,
      markRequiredForNextLevel: 1,
      tokensEarned: 10,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 85,
      championLevel: 6,
      championPoints: 34164,
      lastPlayTime: 1771731084000,
      championPointsSinceLastLevel: 2564,
      championPointsUntilNextLevel: 8436,
      markRequiredForNextLevel: 1,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 950,
      championLevel: 6,
      championPoints: 34100,
      lastPlayTime: 1781387437000,
      championPointsSinceLastLevel: 2500,
      championPointsUntilNextLevel: 8500,
      markRequiredForNextLevel: 1,
      tokensEarned: 20,
      championSeasonMilestone: 2,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'S-': 1,
        },
        rewardMarks: 2,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 236,
      championLevel: 6,
      championPoints: 34065,
      lastPlayTime: 1775021873000,
      championPointsSinceLastLevel: 2465,
      championPointsUntilNextLevel: 8535,
      markRequiredForNextLevel: 1,
      tokensEarned: 7,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 84,
      championLevel: 6,
      championPoints: 33845,
      lastPlayTime: 1777000257000,
      championPointsSinceLastLevel: 2245,
      championPointsUntilNextLevel: 8755,
      markRequiredForNextLevel: 1,
      tokensEarned: 4,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 1,
      championLevel: 6,
      championPoints: 33334,
      lastPlayTime: 1778036726000,
      championPointsSinceLastLevel: 1734,
      championPointsUntilNextLevel: 9266,
      markRequiredForNextLevel: 1,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 131,
      championLevel: 6,
      championPoints: 32244,
      lastPlayTime: 1780331821000,
      championPointsSinceLastLevel: 644,
      championPointsUntilNextLevel: 10356,
      markRequiredForNextLevel: 1,
      tokensEarned: 16,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 23,
      championLevel: 6,
      championPoints: 32037,
      lastPlayTime: 1758091331000,
      championPointsSinceLastLevel: 437,
      championPointsUntilNextLevel: 10563,
      markRequiredForNextLevel: 1,
      tokensEarned: 4,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 55,
      championLevel: 5,
      championPoints: 30249,
      lastPlayTime: 1779338422000,
      championPointsSinceLastLevel: 8649,
      championPointsUntilNextLevel: 1351,
      markRequiredForNextLevel: 1,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 96,
      championLevel: 5,
      championPoints: 29719,
      lastPlayTime: 1771027919000,
      championPointsSinceLastLevel: 8119,
      championPointsUntilNextLevel: 1881,
      markRequiredForNextLevel: 1,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 98,
      championLevel: 5,
      championPoints: 27722,
      lastPlayTime: 1781160685000,
      championPointsSinceLastLevel: 6122,
      championPointsUntilNextLevel: 3878,
      markRequiredForNextLevel: 1,
      tokensEarned: 3,
      championSeasonMilestone: 1,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 8,
      championLevel: 5,
      championPoints: 27498,
      lastPlayTime: 1781645838000,
      championPointsSinceLastLevel: 5898,
      championPointsUntilNextLevel: 4102,
      markRequiredForNextLevel: 1,
      tokensEarned: 6,
      championSeasonMilestone: 0,
      milestoneGrades: ['D+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 164,
      championLevel: 5,
      championPoints: 27046,
      lastPlayTime: 1776497653000,
      championPointsSinceLastLevel: 5446,
      championPointsUntilNextLevel: 4554,
      markRequiredForNextLevel: 1,
      tokensEarned: 4,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 10,
      championLevel: 5,
      championPoints: 26146,
      lastPlayTime: 1781552733000,
      championPointsSinceLastLevel: 4546,
      championPointsUntilNextLevel: 5454,
      markRequiredForNextLevel: 1,
      tokensEarned: 5,
      championSeasonMilestone: 0,
      milestoneGrades: ['B+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 875,
      championLevel: 5,
      championPoints: 25794,
      lastPlayTime: 1762935542000,
      championPointsSinceLastLevel: 4194,
      championPointsUntilNextLevel: 5806,
      markRequiredForNextLevel: 1,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 799,
      championLevel: 5,
      championPoints: 25168,
      lastPlayTime: 1781676998000,
      championPointsSinceLastLevel: 3568,
      championPointsUntilNextLevel: 6432,
      markRequiredForNextLevel: 1,
      tokensEarned: 10,
      championSeasonMilestone: 1,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 887,
      championLevel: 5,
      championPoints: 24855,
      lastPlayTime: 1771475864000,
      championPointsSinceLastLevel: 3255,
      championPointsUntilNextLevel: 6745,
      markRequiredForNextLevel: 1,
      tokensEarned: 10,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 38,
      championLevel: 4,
      championPoints: 23098,
      lastPlayTime: 1779504279000,
      championPointsSinceLastLevel: 10498,
      championPointsUntilNextLevel: -1498,
      markRequiredForNextLevel: 1,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 101,
      championLevel: 5,
      championPoints: 22584,
      lastPlayTime: 1771982615000,
      championPointsSinceLastLevel: 984,
      championPointsUntilNextLevel: 9016,
      markRequiredForNextLevel: 1,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 161,
      championLevel: 5,
      championPoints: 22503,
      lastPlayTime: 1624387449000,
      championPointsSinceLastLevel: 903,
      championPointsUntilNextLevel: 9097,
      markRequiredForNextLevel: 1,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 4,
      championLevel: 5,
      championPoints: 22470,
      lastPlayTime: 1727747896000,
      championPointsSinceLastLevel: 870,
      championPointsUntilNextLevel: 9130,
      markRequiredForNextLevel: 1,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 126,
      championLevel: 4,
      championPoints: 21446,
      lastPlayTime: 1779599759000,
      championPointsSinceLastLevel: 8846,
      championPointsUntilNextLevel: 154,
      markRequiredForNextLevel: 1,
      tokensEarned: 13,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 3,
      championLevel: 4,
      championPoints: 21434,
      lastPlayTime: 1772922045000,
      championPointsSinceLastLevel: 8834,
      championPointsUntilNextLevel: 166,
      markRequiredForNextLevel: 1,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 12,
      championLevel: 4,
      championPoints: 20107,
      lastPlayTime: 1781755047000,
      championPointsSinceLastLevel: 7507,
      championPointsUntilNextLevel: 1493,
      markRequiredForNextLevel: 1,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      milestoneGrades: ['B'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 31,
      championLevel: 4,
      championPoints: 19863,
      lastPlayTime: 1779224738000,
      championPointsSinceLastLevel: 7263,
      championPointsUntilNextLevel: 1737,
      markRequiredForNextLevel: 1,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 904,
      championLevel: 4,
      championPoints: 19701,
      lastPlayTime: 1781729882000,
      championPointsSinceLastLevel: 7101,
      championPointsUntilNextLevel: 1899,
      markRequiredForNextLevel: 1,
      tokensEarned: 8,
      championSeasonMilestone: 0,
      milestoneGrades: ['B+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 36,
      championLevel: 4,
      championPoints: 18380,
      lastPlayTime: 1781747761000,
      championPointsSinceLastLevel: 5780,
      championPointsUntilNextLevel: 3220,
      markRequiredForNextLevel: 1,
      tokensEarned: 10,
      championSeasonMilestone: 1,
      milestoneGrades: ['C+', 'C+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 429,
      championLevel: 4,
      championPoints: 17971,
      lastPlayTime: 1781769332000,
      championPointsSinceLastLevel: 5371,
      championPointsUntilNextLevel: 3629,
      markRequiredForNextLevel: 1,
      tokensEarned: 8,
      championSeasonMilestone: 1,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 32,
      championLevel: 4,
      championPoints: 17939,
      lastPlayTime: 1731205649000,
      championPointsSinceLastLevel: 5339,
      championPointsUntilNextLevel: 3661,
      markRequiredForNextLevel: 1,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 106,
      championLevel: 4,
      championPoints: 17607,
      lastPlayTime: 1750193523000,
      championPointsSinceLastLevel: 5007,
      championPointsUntilNextLevel: 3993,
      markRequiredForNextLevel: 1,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 77,
      championLevel: 4,
      championPoints: 17045,
      lastPlayTime: 1758665890000,
      championPointsSinceLastLevel: 4445,
      championPointsUntilNextLevel: 4555,
      markRequiredForNextLevel: 1,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 897,
      championLevel: 4,
      championPoints: 16788,
      lastPlayTime: 1781422761000,
      championPointsSinceLastLevel: 4188,
      championPointsUntilNextLevel: 4812,
      markRequiredForNextLevel: 1,
      tokensEarned: 5,
      championSeasonMilestone: 0,
      milestoneGrades: ['C'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 14,
      championLevel: 4,
      championPoints: 16639,
      lastPlayTime: 1781759307000,
      championPointsSinceLastLevel: 4039,
      championPointsUntilNextLevel: 4961,
      markRequiredForNextLevel: 1,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      milestoneGrades: ['B+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 804,
      championLevel: 4,
      championPoints: 16509,
      lastPlayTime: 1781666831000,
      championPointsSinceLastLevel: 3909,
      championPointsUntilNextLevel: 5091,
      markRequiredForNextLevel: 1,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      milestoneGrades: ['B'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 81,
      championLevel: 4,
      championPoints: 15829,
      lastPlayTime: 1765355193000,
      championPointsSinceLastLevel: 3229,
      championPointsUntilNextLevel: 5771,
      markRequiredForNextLevel: 1,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 39,
      championLevel: 4,
      championPoints: 15433,
      lastPlayTime: 1781682545000,
      championPointsSinceLastLevel: 2833,
      championPointsUntilNextLevel: 6167,
      markRequiredForNextLevel: 1,
      tokensEarned: 3,
      championSeasonMilestone: 1,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 110,
      championLevel: 4,
      championPoints: 15230,
      lastPlayTime: 1770094934000,
      championPointsSinceLastLevel: 2630,
      championPointsUntilNextLevel: 6370,
      markRequiredForNextLevel: 1,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 200,
      championLevel: 4,
      championPoints: 15157,
      lastPlayTime: 1779846662000,
      championPointsSinceLastLevel: 2557,
      championPointsUntilNextLevel: 6443,
      markRequiredForNextLevel: 1,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 51,
      championLevel: 4,
      championPoints: 13645,
      lastPlayTime: 1781640271000,
      championPointsSinceLastLevel: 1045,
      championPointsUntilNextLevel: 7955,
      markRequiredForNextLevel: 1,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      milestoneGrades: ['B'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 901,
      championLevel: 4,
      championPoints: 13296,
      lastPlayTime: 1780087971000,
      championPointsSinceLastLevel: 696,
      championPointsUntilNextLevel: 8304,
      markRequiredForNextLevel: 1,
      tokensEarned: 8,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 111,
      championLevel: 3,
      championPoints: 12500,
      lastPlayTime: 1780943384000,
      championPointsSinceLastLevel: 6500,
      championPointsUntilNextLevel: 100,
      markRequiredForNextLevel: 0,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 136,
      championLevel: 3,
      championPoints: 12378,
      lastPlayTime: 1771729736000,
      championPointsSinceLastLevel: 6378,
      championPointsUntilNextLevel: 222,
      markRequiredForNextLevel: 0,
      tokensEarned: 5,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 16,
      championLevel: 3,
      championPoints: 12198,
      lastPlayTime: 1778792851000,
      championPointsSinceLastLevel: 6198,
      championPointsUntilNextLevel: 402,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 33,
      championLevel: 3,
      championPoints: 12057,
      lastPlayTime: 1660783771000,
      championPointsSinceLastLevel: 6057,
      championPointsUntilNextLevel: 543,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 268,
      championLevel: 3,
      championPoints: 11809,
      lastPlayTime: 1775282803000,
      championPointsSinceLastLevel: 5809,
      championPointsUntilNextLevel: 791,
      markRequiredForNextLevel: 0,
      tokensEarned: 7,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 50,
      championLevel: 3,
      championPoints: 11772,
      lastPlayTime: 1759374818000,
      championPointsSinceLastLevel: 5772,
      championPointsUntilNextLevel: 828,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 67,
      championLevel: 3,
      championPoints: 10952,
      lastPlayTime: 1736232804000,
      championPointsSinceLastLevel: 4952,
      championPointsUntilNextLevel: 1648,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 876,
      championLevel: 3,
      championPoints: 9751,
      lastPlayTime: 1777905033000,
      championPointsSinceLastLevel: 3751,
      championPointsUntilNextLevel: 2849,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 27,
      championLevel: 3,
      championPoints: 9720,
      lastPlayTime: 1779173543000,
      championPointsSinceLastLevel: 3720,
      championPointsUntilNextLevel: 2880,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 28,
      championLevel: 3,
      championPoints: 9614,
      lastPlayTime: 1767327046000,
      championPointsSinceLastLevel: 3614,
      championPointsUntilNextLevel: 2986,
      markRequiredForNextLevel: 0,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 516,
      championLevel: 3,
      championPoints: 9553,
      lastPlayTime: 1730240356000,
      championPointsSinceLastLevel: 3553,
      championPointsUntilNextLevel: 3047,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 18,
      championLevel: 3,
      championPoints: 9113,
      lastPlayTime: 1781644307000,
      championPointsSinceLastLevel: 3113,
      championPointsUntilNextLevel: 3487,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      milestoneGrades: ['B'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 42,
      championLevel: 3,
      championPoints: 8911,
      lastPlayTime: 1781757365000,
      championPointsSinceLastLevel: 2911,
      championPointsUntilNextLevel: 3689,
      markRequiredForNextLevel: 0,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      milestoneGrades: ['B+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 102,
      championLevel: 3,
      championPoints: 8882,
      lastPlayTime: 1649976749000,
      championPointsSinceLastLevel: 2882,
      championPointsUntilNextLevel: 3718,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 163,
      championLevel: 3,
      championPoints: 8841,
      lastPlayTime: 1778743970000,
      championPointsSinceLastLevel: 2841,
      championPointsUntilNextLevel: 3759,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 9,
      championLevel: 3,
      championPoints: 8576,
      lastPlayTime: 1760246417000,
      championPointsSinceLastLevel: 2576,
      championPointsUntilNextLevel: 4024,
      markRequiredForNextLevel: 0,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 143,
      championLevel: 3,
      championPoints: 8316,
      lastPlayTime: 1781668618000,
      championPointsSinceLastLevel: 2316,
      championPointsUntilNextLevel: 4284,
      markRequiredForNextLevel: 0,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      milestoneGrades: ['B+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 20,
      championLevel: 3,
      championPoints: 8268,
      lastPlayTime: 1708239887000,
      championPointsSinceLastLevel: 2268,
      championPointsUntilNextLevel: 4332,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 79,
      championLevel: 3,
      championPoints: 8205,
      lastPlayTime: 1753928983000,
      championPointsSinceLastLevel: 2205,
      championPointsUntilNextLevel: 4395,
      markRequiredForNextLevel: 0,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 103,
      championLevel: 3,
      championPoints: 8029,
      lastPlayTime: 1745724389000,
      championPointsSinceLastLevel: 2029,
      championPointsUntilNextLevel: 4571,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 166,
      championLevel: 3,
      championPoints: 7441,
      lastPlayTime: 1778788643000,
      championPointsSinceLastLevel: 1441,
      championPointsUntilNextLevel: 5159,
      markRequiredForNextLevel: 0,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 74,
      championLevel: 3,
      championPoints: 7367,
      lastPlayTime: 1509063299000,
      championPointsSinceLastLevel: 1367,
      championPointsUntilNextLevel: 5233,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 68,
      championLevel: 3,
      championPoints: 7349,
      lastPlayTime: 1777594346000,
      championPointsSinceLastLevel: 1349,
      championPointsUntilNextLevel: 5251,
      markRequiredForNextLevel: 0,
      tokensEarned: 3,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 432,
      championLevel: 3,
      championPoints: 7198,
      lastPlayTime: 1768981353000,
      championPointsSinceLastLevel: 1198,
      championPointsUntilNextLevel: 5402,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 53,
      championLevel: 3,
      championPoints: 7047,
      lastPlayTime: 1780257603000,
      championPointsSinceLastLevel: 1047,
      championPointsUntilNextLevel: 5553,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 240,
      championLevel: 3,
      championPoints: 6717,
      lastPlayTime: 1738385914000,
      championPointsSinceLastLevel: 717,
      championPointsUntilNextLevel: 5883,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 43,
      championLevel: 3,
      championPoints: 6618,
      lastPlayTime: 1775796514000,
      championPointsSinceLastLevel: 618,
      championPointsUntilNextLevel: 5982,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 99,
      championLevel: 3,
      championPoints: 6595,
      lastPlayTime: 1771309113000,
      championPointsSinceLastLevel: 595,
      championPointsUntilNextLevel: 6005,
      markRequiredForNextLevel: 0,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 78,
      championLevel: 3,
      championPoints: 6431,
      lastPlayTime: 1731195387000,
      championPointsSinceLastLevel: 431,
      championPointsUntilNextLevel: 6169,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 115,
      championLevel: 3,
      championPoints: 6410,
      lastPlayTime: 1762419307000,
      championPointsSinceLastLevel: 410,
      championPointsUntilNextLevel: 6190,
      markRequiredForNextLevel: 0,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 518,
      championLevel: 3,
      championPoints: 6322,
      lastPlayTime: 1771714184000,
      championPointsSinceLastLevel: 322,
      championPointsUntilNextLevel: 6278,
      markRequiredForNextLevel: 0,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 350,
      championLevel: 3,
      championPoints: 6272,
      lastPlayTime: 1779051842000,
      championPointsSinceLastLevel: 272,
      championPointsUntilNextLevel: 6328,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 223,
      championLevel: 3,
      championPoints: 6173,
      lastPlayTime: 1626554688000,
      championPointsSinceLastLevel: 173,
      championPointsUntilNextLevel: 6427,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 21,
      championLevel: 2,
      championPoints: 5941,
      lastPlayTime: 1764663362000,
      championPointsSinceLastLevel: 4141,
      championPointsUntilNextLevel: 59,
      markRequiredForNextLevel: 0,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 60,
      championLevel: 2,
      championPoints: 5940,
      lastPlayTime: 1781072316000,
      championPointsSinceLastLevel: 4140,
      championPointsUntilNextLevel: 60,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 421,
      championLevel: 2,
      championPoints: 5939,
      lastPlayTime: 1663740160000,
      championPointsSinceLastLevel: 4139,
      championPointsUntilNextLevel: 61,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 221,
      championLevel: 2,
      championPoints: 5565,
      lastPlayTime: 1773461846000,
      championPointsSinceLastLevel: 3765,
      championPointsUntilNextLevel: 435,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 48,
      championLevel: 2,
      championPoints: 5419,
      lastPlayTime: 1761172204000,
      championPointsSinceLastLevel: 3619,
      championPointsUntilNextLevel: 581,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 22,
      championLevel: 2,
      championPoints: 5410,
      lastPlayTime: 1766989063000,
      championPointsSinceLastLevel: 3610,
      championPointsUntilNextLevel: 590,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 76,
      championLevel: 2,
      championPoints: 5339,
      lastPlayTime: 1763879080000,
      championPointsSinceLastLevel: 3539,
      championPointsUntilNextLevel: 661,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 7,
      championLevel: 2,
      championPoints: 5183,
      lastPlayTime: 1729886981000,
      championPointsSinceLastLevel: 3383,
      championPointsUntilNextLevel: 817,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 145,
      championLevel: 2,
      championPoints: 5124,
      lastPlayTime: 1781426300000,
      championPointsSinceLastLevel: 3324,
      championPointsUntilNextLevel: 876,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      milestoneGrades: ['C+'],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 25,
      championLevel: 2,
      championPoints: 4936,
      lastPlayTime: 1621726168000,
      championPointsSinceLastLevel: 3136,
      championPointsUntilNextLevel: 1064,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 19,
      championLevel: 2,
      championPoints: 4536,
      lastPlayTime: 1577223017000,
      championPointsSinceLastLevel: 2736,
      championPointsUntilNextLevel: 1464,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 57,
      championLevel: 2,
      championPoints: 4508,
      lastPlayTime: 1752731339000,
      championPointsSinceLastLevel: 2708,
      championPointsUntilNextLevel: 1492,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 6,
      championLevel: 2,
      championPoints: 4481,
      lastPlayTime: 1780640217000,
      championPointsSinceLastLevel: 2681,
      championPointsUntilNextLevel: 1519,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 117,
      championLevel: 2,
      championPoints: 4351,
      lastPlayTime: 1764742360000,
      championPointsSinceLastLevel: 2551,
      championPointsUntilNextLevel: 1649,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 72,
      championLevel: 2,
      championPoints: 4305,
      lastPlayTime: 1776905510000,
      championPointsSinceLastLevel: 2505,
      championPointsUntilNextLevel: 1695,
      markRequiredForNextLevel: 0,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 222,
      championLevel: 2,
      championPoints: 4240,
      lastPlayTime: 1771716831000,
      championPointsSinceLastLevel: 2440,
      championPointsUntilNextLevel: 1760,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 89,
      championLevel: 2,
      championPoints: 4095,
      lastPlayTime: 1780907084000,
      championPointsSinceLastLevel: 2295,
      championPointsUntilNextLevel: 1905,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 83,
      championLevel: 2,
      championPoints: 3983,
      lastPlayTime: 1777592302000,
      championPointsSinceLastLevel: 2183,
      championPointsUntilNextLevel: 2017,
      markRequiredForNextLevel: 0,
      tokensEarned: 2,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 69,
      championLevel: 2,
      championPoints: 3887,
      lastPlayTime: 1771123641000,
      championPointsSinceLastLevel: 2087,
      championPointsUntilNextLevel: 2113,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 910,
      championLevel: 2,
      championPoints: 3363,
      lastPlayTime: 1781249340000,
      championPointsSinceLastLevel: 1563,
      championPointsUntilNextLevel: 2637,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 1,
      milestoneGrades: [],
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 61,
      championLevel: 2,
      championPoints: 3238,
      lastPlayTime: 1502762754000,
      championPointsSinceLastLevel: 1438,
      championPointsUntilNextLevel: 2762,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 40,
      championLevel: 2,
      championPoints: 3197,
      lastPlayTime: 1642127908000,
      championPointsSinceLastLevel: 1397,
      championPointsUntilNextLevel: 2803,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 150,
      championLevel: 2,
      championPoints: 3093,
      lastPlayTime: 1488589001000,
      championPointsSinceLastLevel: 1293,
      championPointsUntilNextLevel: 2907,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 154,
      championLevel: 2,
      championPoints: 2772,
      lastPlayTime: 1749963491000,
      championPointsSinceLastLevel: 972,
      championPointsUntilNextLevel: 3228,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 893,
      championLevel: 2,
      championPoints: 2432,
      lastPlayTime: 1775893191000,
      championPointsSinceLastLevel: 632,
      championPointsUntilNextLevel: 3568,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 498,
      championLevel: 2,
      championPoints: 2392,
      lastPlayTime: 1686772444000,
      championPointsSinceLastLevel: 592,
      championPointsUntilNextLevel: 3608,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 420,
      championLevel: 2,
      championPoints: 2343,
      lastPlayTime: 1578016012000,
      championPointsSinceLastLevel: 543,
      championPointsUntilNextLevel: 3657,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 113,
      championLevel: 2,
      championPoints: 2327,
      lastPlayTime: 1760388358000,
      championPointsSinceLastLevel: 527,
      championPointsUntilNextLevel: 3673,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 134,
      championLevel: 2,
      championPoints: 1986,
      lastPlayTime: 1761283769000,
      championPointsSinceLastLevel: 186,
      championPointsUntilNextLevel: 4014,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 526,
      championLevel: 2,
      championPoints: 1874,
      lastPlayTime: 1739157579000,
      championPointsSinceLastLevel: 74,
      championPointsUntilNextLevel: 4126,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 497,
      championLevel: 1,
      championPoints: 1529,
      lastPlayTime: 1766993174000,
      championPointsSinceLastLevel: 1529,
      championPointsUntilNextLevel: 271,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 15,
      championLevel: 1,
      championPoints: 1378,
      lastPlayTime: 1672202419000,
      championPointsSinceLastLevel: 1378,
      championPointsUntilNextLevel: 422,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 360,
      championLevel: 1,
      championPoints: 1320,
      lastPlayTime: 1753057984000,
      championPointsSinceLastLevel: 1320,
      championPointsUntilNextLevel: 480,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 201,
      championLevel: 1,
      championPoints: 1226,
      lastPlayTime: 1764747719000,
      championPointsSinceLastLevel: 1226,
      championPointsUntilNextLevel: 574,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 37,
      championLevel: 1,
      championPoints: 1133,
      lastPlayTime: 1758577097000,
      championPointsSinceLastLevel: 1133,
      championPointsUntilNextLevel: 667,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 44,
      championLevel: 1,
      championPoints: 1070,
      lastPlayTime: 1471638712000,
      championPointsSinceLastLevel: 1070,
      championPointsUntilNextLevel: 730,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 800,
      championLevel: 1,
      championPoints: 972,
      lastPlayTime: 1766875769000,
      championPointsSinceLastLevel: 972,
      championPointsUntilNextLevel: 828,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 133,
      championLevel: 1,
      championPoints: 920,
      lastPlayTime: 1489372290000,
      championPointsSinceLastLevel: 920,
      championPointsUntilNextLevel: 880,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 147,
      championLevel: 1,
      championPoints: 853,
      lastPlayTime: 1772001482000,
      championPointsSinceLastLevel: 853,
      championPointsUntilNextLevel: 947,
      markRequiredForNextLevel: 0,
      tokensEarned: 1,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 26,
      championLevel: 1,
      championPoints: 647,
      lastPlayTime: 1550004423000,
      championPointsSinceLastLevel: 647,
      championPointsUntilNextLevel: 1153,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 235,
      championLevel: 1,
      championPoints: 325,
      lastPlayTime: 1612723881000,
      championPointsSinceLastLevel: 325,
      championPointsUntilNextLevel: 1475,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 142,
      championLevel: 1,
      championPoints: 227,
      lastPlayTime: 1533226830000,
      championPointsSinceLastLevel: 227,
      championPointsUntilNextLevel: 1573,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 412,
      championLevel: 1,
      championPoints: 148,
      lastPlayTime: 1477165336000,
      championPointsSinceLastLevel: 148,
      championPointsUntilNextLevel: 1652,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
    {
      puuid: userPuuid,
      championId: 427,
      championLevel: 1,
      championPoints: 139,
      lastPlayTime: 1563418319000,
      championPointsSinceLastLevel: 139,
      championPointsUntilNextLevel: 1661,
      markRequiredForNextLevel: 0,
      tokensEarned: 0,
      championSeasonMilestone: 0,
      nextSeasonMilestone: {
        requireGradeCounts: {
          'A-': 1,
        },
        rewardMarks: 1,
        bonus: false,
        totalGamesRequires: 1,
      },
    },
  ] as unknown as ChampionMastery[]
};