export enum GUIDE_REPORT_REASON {
  INAPPROPRIATE_CONTENT = 'INAPPROPRIATE_CONTENT',
  INCORRECT_INFORMATION = 'INCORRECT_INFORMATION',
  SPAM = 'SPAM',
  ADVERTISING = 'ADVERTISING',
  HARASSMENT = 'HARASSMENT',
  COPYRIGHT = 'COPYRIGHT',
  EXPLOIT_OR_CHEATING = 'EXPLOIT_OR_CHEATING',
  OTHER = 'OTHER',
}

export enum GUIDE_REPORT_STATUS {
  OPENED = 'OPENED',
  ARCHIVED = 'ARCHIVED',
}

export enum GUIDE_REPORT_ACTION_TAKEN {
  BLOCKED = 'BLOCKED',
  DISMISS = 'DISMISS',
  WAITING = 'WAITING'
}