export enum GuideReportReason {
  INAPPROPRIATE_CONTENT = 'INAPPROPRIATE_CONTENT',
  INCORRECT_INFORMATION = 'INCORRECT_INFORMATION',
  SPAM = 'SPAM',
  ADVERTISING = 'ADVERTISING',
  HARASSMENT = 'HARASSMENT',
  COPYRIGHT = 'COPYRIGHT',
  EXPLOIT_OR_CHEATING = 'EXPLOIT_OR_CHEATING',
  OTHER = 'OTHER',
}